---
title: "gsoc2019"
author: "Sayani Gupta"
date: "3/20/2019"
output: html_document
---

  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Background

<!-- Australian smart meters report large quantities of measurements on energy usage every half an hour for every households. Households are distributed geographically and they can differ with respect to demographic properties such as lifestyle or livability choices like usage and existence of solar panels, central heating or air conditioning. Also some households might consist of night owls, while other might have morning larks. Some might work from home most days in a week and have uniform energy usage through out the week, while others have very little usage in the weekdays and high usage only on weekends. Some households might be travelers who are always out on any extended/ public holidays and school breaks. -->


<!-- It is common to see aggregates of usage across households, total kwh used each half hour by state, for example, because energy companies need to understand maximum loads that they will have to plan ahead to accommodate. But studying overall energy use hides the distributions of usage at finer scales, and making it more difficult to find solutions to improve energy efficiency. -->

<!-- To illustrate further, if the energy companies are more cognizant of the energy usage of their customers, they might use the excess energy in times of off-peak demand for few households to charge solar batteries or reward households for using their energy mindfully in case of peak demand. Customers, for example, can view the distribution of their usage in peak demand periods compared to households with similar demographics and and save some dollars on their electricity bill.  -->


Considerable data is accumulated by sensors today. An example is data measuring energy usage on a fine scale using smart meters. Smart meters are installed on many households in many countries now. Providing tools to explore this type of data is an important activity. Because of the large volume of data, using probability distributions for display is a potentially useful approach. Probability distributions are induced by various aggregations of the data, by temporal components, by spatial region, by type of household. 

The idea for this package is to provide a methods to operate on time in an automated way, to deconstruct it in many different ways. Deconstructions of time that respect the linear progression of time like days, weeks and months are defined as linear time granularities and those that accommodate for periodicities in time like hour of the day or day of the month are defined as circular granularities or calendar categorizations. This package will provide the methods to exhaustively construct granularities, and provide automatic checks on the feasibility of a particular granularity. 

The package will provide these tenchiques into the tidy workflow, so that probability distributions can be examined in the range of graphics available in the ggplot2 package.


# Related work

- *_lubridate_* is an R package that makes it easier to work with time and also has functions for creating calendar categorizations like hour of the day, day of the week, minutes of the hour. But it mostly creates calendar categorizations that are one step up. The framework proposed will allow creating calendar categorizations that are more than one step ahead, for example,  hour of the week or one step up that are not present in lubridate package like week of the month.

- Calendar based graphics in the package *_sugrrants_* help explore data across linear time granularities in a calendar format, whereas this package would help explore circular time granularities.

- *_ggplot2_* facilitates the process of mapping different variables to a 2D frame through grammar of graphics. But it does not tell us which all variables to plot together to promote exploration of data.
If we define time variables that facilitate exploration as harmonies and those that do not as clashes, the proposed framework would provide the list of harmonies given a time variable.

- This will use as inputs *_tsibble_* objects which complement the tibble and extend the tidyverse concept to temporal data.

# Details of your coding project

1. Develop an R package
  - with functions to create circular time granularities that are multiple step up in time
  - with functions to create list of visualizations of harmonies given a circular time granularity 
  - providing advice using suitable summary statistics on whether probability distributions should be plotted

2. Getting familiar with shiny UI development and creating a dashboard that enables all these functionalities

3. Experiment with probability visualization techniques that are not yet in the tidyverse framework and building new geom class for them. 
4. Complete set of features to be well documented

# Expected impact

The package would facilitate a tidy workflow for exploring probability distributions of variables defined on temporal granularties. Being able to derive useful summaries and exhaustive visual graphics for deriving multiple perspectives of data will promote efficient exploration of data.

# Mentors

- Dianne Cook <dicook@monash.edu> 
- Antony Unwin 
  
  
MENTORS: write several tests that potential students can do to demonstrate their capabilities for this particular project. Ask some hard questions that will give you insight about how the students write code to solve problems. You’ll see that the harder the questions that you ask, the easier it will be for you to choose between the students that apply for your project! Please modify the suggestions below to make them specific for your project.

Easy: something that any useR should be able to do, e.g. download some existing package listed in the Related Work, and run it on some example data.

Medium: something a bit more complicated. You can encourage students to write a script or some functions that show their R coding abilities.

Hard: Can the student write a package with Rd files, tests, and vigettes? If your package interfaces with non-R code, can the student write in that other language?
  
  
  
