---
title: "gsoc2019_tests"
author: "Sayani Gupta"
date: "3/22/2019"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, cache=TRUE)
# Load any R packages you need here
library(ggplot2)
library(dplyr)
library(lubridate)
library(ggplot2)
library(lvplot)
library(ggridges)
library(tsibbledata)
```


Easy: Explore the data aus_elec (Half-hourly electricity demand for five Australian states) from the package tsibbledata and create five different probability distribution plots for each month. For example, boxplot which shows median, quartile boundaries, hinges, whiskers and outliers is one of the ways to display distribution of data. 


```{r easy, echo=TRUE}

distinct_State <- aus_elec %>%  distinct(State)

# Picking Queensland 

qld_elec <- aus_elec %>%
            filter(State =="Queensland") %>%
            mutate(data_month = month(Time))

qld_tr <- qld_elec %>%
          .$Time %>% range()

# Boxplot
qld_elec %>%
  filter(year(Time) %in% c(2012, 2013, 2014)) %>%                     ggplot(aes(as.factor(data_month),Demand))+
  geom_boxplot() + 
  ylab("Demand in MW") +
  xlab("Months") +
  scale_x_discrete(breaks=seq(1,12,1)) +             theme(legend.position = "bottom",strip.text = element_text(size = 7, margin = margin())) + ggtitle("Boxplot of the demand for QLD")

# Ridge Plot

qld_elec %>% 
  filter(year %in% c(2012, 2013, 2014))%>% 
  ggplot(aes(x = Demand,y=as.factor(data_month),group=data_month)) +   geom_density_ridges2() +
  xlab("Demand in MW") +
  ylab("Months")+ 
  scale_x_continuous(breaks = seq(2000,10000,3000)) +     theme(legend.position = "bottom",strip.text = element_text(size = 7, margin = margin())) + ggtitle("(e) Ridge plot")


VIC%>% filter(year %in% c(2012, 2013, 2014),Indx_Wk_Month %in% c(1,2,4))%>% ggplot(aes(as.factor(Indx_Day_Month),OperationalLessIndustrial)) + geom_violin(alpha = 0.03)+ facet_wrap(~Indx_Wk_Month,nrow=3) + ylab("") + xlab("Days of the Month") + theme(legend.position = "bottom",strip.text = element_text(size = 7, margin = margin())) + scale_x_discrete(breaks=seq(0,31,5))+ scale_y_continuous(breaks = seq(2000,9000,2000))+ ggtitle("(d) Violin plot")
VIC%>% dplyr:::filter(year %in% c(2012, 2013, 2014),Indx_Wk_Month %in% c(1,2,5),Indx_Wk_Yr <20)%>% ggplot(aes(x=OperationalLessIndustrial,y=as.factor(Indx_Wk_Yr),group=Indx_Wk_Yr)) + geom_density_ridges2() +facet_wrap(~Indx_Wk_Month) + xlab("Electricity Demand [KWh]") + ylab("Weeks of the Year") + scale_x_continuous(breaks = seq(2000,10000,3000)) + theme(legend.position = "bottom",strip.text = element_text(size = 7, margin = margin())) + ggtitle("(e) Ridge plot")







```

