---
title: "Initiate codebase"
author: "Sayani Gupta"
date: "05/06/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tsibble)
library(ggplot2)
```

```{r}
data_nyc <- tsibbledata::nyc_bikes 
data_nyc %>% summary()
# one year data for 2018 

start_station <- data_nyc %>% distinct(start_station)

end_station <- data_nyc %>% distinct(end_station)

unique_start_end <- data_nyc %>% as_tibble() %>% ungroup() %>%  group_by(start_station, end_station) %>% tally() %>% arrange(-n) %>% head()

bike_combo_1 <- data_nyc %>% filter(start_station %in% c(3186, 3203) | end_station %in% c(3186, 3203))
```

```{r BUILD, echo=TRUE}

parse_exp <- function(y) {
  if (y == "1") {
    value <- 1
  }
  else {
    value <- parse(text = paste0(y, "(x)"))
  }
  return(value)
}


nest <- function(gran1, gran2, x, ...) { # for periodic granularities that are either strictly less than month or strictly more than month
  gran1_ordr1 <- g_order(gran1, order = 1)

  if (g_order(gran1, gran2) == 1) {
    one_order <- lookup_table$convertfun[lookup_table$granularity %>% match(x = gran1)]
    return(eval(parse_exp(one_order)))
  } else {
    value <- nest(gran1, gran1_ordr1, x) +
      gran_convert(gran1, gran1_ordr1) *
        (nest(gran1_ordr1, gran2, x) - 1)
    return(value)
  }
}


anest <- function(gran1, gran2, x, ...) { # for aperiodic granularities - gran1 less than month and gran2 more than or equal to month

  index_gran2 <- granularity %>% match(x = gran2)
  day_gran2 <- eval(parse_exp(lookup_table$convertday[index_gran2]))
  c_gran1_day <- gran_convert(gran1, "day")

 if(g_order("minute", "day")>=0)
 {
  value = nest(gran1, "day", x) + c_gran1_day*(day_gran2 - 1)
 }
 else
 {
   value = ceiling(day_gran2/c_gran1_day)
 }
}


# the lookup table - this needs to be changed if other granularities are included
lookup_table <- tibble::tibble(
  granularity = c("second", "minute", "qhour", "hhour", "hour", "day", "week", "fortnight", "month", "quarter", "semester", "year"),
  constant = c(60, 15, 2, 2, 24, 7, 2, 2, 3, 2, 2, 1),
  convertfun = c("lubridate::second", "minute_qhour", "qhour_hhour", "hhour_hour", "lubridate::hour", "lubridate::wday", "week_fortnight", "fortnight_month", "month_quarter", "quarter_semester", "semester_year", 1),
  convertday = c("second_day", "minute_day", "qhour_day", "hhour_day", "lubridate::hour",1, "lubridate::wday", "day_fortnight", "lubridate::mday", "lubridate::qday", "day_semester", "lubridate::yday"),
)

# provides the order difference between two granularities, also provide the upper granularity given the order
g_order <- function(gran1, gran2 = NULL, order = NULL) {
  granularity <- lookup_table$granularity
  index_gran1 <- granularity %>% match(x = gran1)
  if (!is.null(gran2)) {
    index_gran2 <- granularity %>% match(x = gran2)
    return(index_gran2 - index_gran1)
  }
  if (!is.null(order)) {
    return(granularity[index_gran1 + order])
  }
}

# provides the conversion factor between two granularities

gran_convert <- function(a, b) {
  granularity <- lookup_table$granularity
  conv_fac <- lookup_table %>% .$constant
  index_gran1 <- granularity %>% match(x = a)
  if (g_order(a, b) == 0) {
    return(1)
  }
  else {
    return(conv_fac[index_gran1] * gran_convert(g_order(a, order = 1), b))
  }
}

second_minute <- function(x) {
  lubridate::second(x)
}

minute_qhour <- function(x) {
  lubridate::minute(x) %% 15 + 1
}

qhour_hhour <- function(x) {
  dplyr::if_else((lubridate::minute(x) %% 30 + 1) <= 15, 1, 2)
}

hhour_hour <- function(x) {
  dplyr::if_else(lubridate::minute(x) <= 30, 1, 2)
}

week_fortnight <- function(x) {
  dplyr::if_else((lubridate::yday(x) %/% 14 + 1) <= 14, 1, 2)
}

month_quarter <- function(x) {
  value <- lubridate::month(x) %% 3
  dplyr::if_else(value == 0, 3, value)
  # otherwise remainder will change the label of the largest value to zero
}

quarter_semester <- function(x) {
  value <- lubridate::quarter(x) %% 2
  dplyr::if_else(value == 0, 2, value)
  # otherwise remainder will change the label of the largest value to zero
}

semester_year <- function(x) {
  lubridate::semester(x)
}


# convert day functions

qhour_day <- function(x) {

  # finds which quarter of the day
  ceiling(lubridate::minute(x) / 15) + 4 * (lubridate::hour(x))
}

hhour_day <- function(x) {
  (lubridate::hour(x) * 60 + lubridate::minute(x)) / 30
}

minute_day <- function(x) {
  lubridate::minute(x) + (lubridate::hour(x) - 1) * 60
}
second_day <- function(x) {
  lubridate::second(x) + (lubridate::hour(x) - 1) * 60 * 60
}


day_semester <- function(x) {

  # finds day of the semester
  which_sem <- lubridate::semester(x)
  day_x <- lubridate::yday(x)
  year_leap <- lubridate::leap_year(x)
  div_indx <- dplyr::if_else(year_leap == "FALSE", 182, 183)
  dplyr::if_else(which_sem == 1, day_x, day_x - div_indx + 1)
}

day_fortnight <- function(x)
{
  value = lubridate::yday(x) %/% 14
  dplyr::if_else(value==0, 14, value)
}

```
```{r}
#usage of functions
data_nyc_gran <- bike_combo_1  %>% mutate(hour_day = nest("hour", "day", start_time),
                     month_year =   nest("month", "year", start_time),
                     day_week   = nest("day", "week", start_time),
                     hhour_day   = nest("hhour", "day", start_time))

```

<!-- # ```{r} -->
<!-- # data_nyc_gran %>% -->
<!-- #   as_tibble %>%  -->
<!-- #   group_by(hour_day, month_year) %>%  -->
<!-- #   summarise(daily_tot = n()) %>%  -->
<!-- #   ggplot(aes(x=hour_day, y=daily_tot)) +  -->
<!-- #   geom_line() +  -->
<!-- #   facet_wrap(~month_year) -->
<!-- #  -->
<!-- # # -->
<!-- # data_nyc_gran %>% -->
<!-- #   as_tibble %>%  -->
<!-- #   group_by(hhour_day, day_week) %>%  -->
<!-- #   summarise(daily_tot = n()) %>%  -->
<!-- #   ggplot(aes(x=hhour_day, y=daily_tot)) +  -->
<!-- #   geom_line() +  -->
<!-- #   facet_wrap(~day_week) -->

```

# Building plot functions for automatic plot titles

```{r granplot, echo=TRUE}
granplot = function(x, y) {
    data_nyc_gran %>% as_tibble %>%  group_by(!!sym(x), !!sym(y)) %>% 
    summarise(ecount = n()) %>% 
     ggplot(aes(x = !!sym(x), y = ecount)) +
          geom_line() +
          theme_bw() + 
          facet_wrap(as.formula(paste("~", y))) + 
          ylab("Total Count") + 
          ggtitle(paste0("Plot of ", x, " given ", y))
}

granplot("hhour_day",  "day_week")
granplot("hour_day",  "month_year")
```


